### ISSUE TITLE
Bookmarks are not added to the top of the selected folder

### ISSUE THREAD

**Issue by peter099** [teddy-gustiaux/default-bookmark-folder#154]
In 'Firefox built-in bookmarking' i have enabled the option 'Add new bookmarks to the top of the selected folder' but bookmarks are still added to the bottom of the selected folder. 

I am using Firefox 71 on Windows 7.

**Comment by peter099** [comment]
I think i misunderstood how this extension works. I thought the option 'Add new bookmarks to the top of the selected folder' will work for the sub-folders of the selected folder, but i guess it doesn't.

**Comment by loopernow** [comment]
Are you sure you are testing the feature by using Ctrl-D or Bookmark This Page, the built-in Firefox options? The option to add to the top of the folder when using the extension's context-menu entry or star button is a different option.

It is working for me (just another user).

**Comment by teddy-gustiaux** [comment]
Thank you both for your feedback on this!

@peter099 you are correct, the option "_Add new bookmarks to the top of the selected folder_" only words for the selected folder, as indicated in the label of the setting.

@loopernow is also correct to point out that the option for the built-in bookmarking and the one for the quick bookmarking are separate. He also reported an issue regarding this option when selecting the default location with the Firefox built-in bookmarking (#172), which will be fixed with the next version of the add-on.

Please check your settings and make sure they are configured as you intended. If you are still experiencing problem, please feel free to open a new issue. 🙂 I will close this one in the meantime.
