### ISSUE TITLE
Add folder to top does not work if Firefox default is the chosen selection

### ISSUE THREAD

**Issue by loopernow** [teddy-gustiaux/default-bookmark-folder#172]
# This is a Bug Report

## Description
"Add new folders of bookmarked tabs to the top" does not work if "No folder selected" is the chosen place to add new folders.

## Steps to reproduce the problem

1. Go to extension's options, to Firefox built-in bookmarking
2. In the bookmarking multiple selected tabs at once section, turn on "Add new folders of..tabs to the top" option.
3. Make sure "No folder selected...default" is the chosen location where new folders of tabs will be added
4. Use Ctrl-Shift-D to bookmark a new folder of tabs
5. Open the Bookmarks menu to observe that the new folder has been added to the bottom of the Bookmarks Menu

## Expected behavior
The added folder of tabs should be added to the top of the Bookmarks Menu

## Specifications

- Version of the add-on: 2.11.0
- Firefox edition: Firefox (regular edition)
- Firefox version: 72.0.2
- Firefox language: English 
- Platform/OS: Windows 

## Additional context
Workaround: Select "Bookmarks Menu" as the location for new folders of bookmarked tabs, instead of "No folder selected." Added folders of tabs will now be added to the top of the Bookmarks Menu folder.

**Comment by teddy-gustiaux** [comment]
Thank you for reporting this problem @loopernow! With all the details you provided, it was easy to find. It will be fixed in the next version to be released soon. 🙂

**Comment by loopernow** [comment]
You're welcome and thank you! :)

**Comment by Chilius** [comment]
Is it possible to turn this change off as an option?
I think it's highly annoying the way it works now since version 2.12.0 so i went back to 2.11.0

When i drag and drop an url from the address bar to my default folder, the url doesn't stay at the location i drop it, but instead it now always drops the url to the top or bottom of the list because of this "bug fix".

I can understand that some people like this behaviour, but i certainly don't.
So i hope you can make this an option instead of making this the default behaviour of the addon.

Personally i think the addon should only work when using the "Quick bookmarking" button and it should not interfere with the default way firefox handles bookmarks when all the options under the "Firefox built-in bookmarking" tab are switches off.
