### ISSUE TITLE
chosen option does not run

### ISSUE THREAD

**Issue by wulfstoe** [teddy-gustiaux/default-bookmark-folder#45]
hello,

you wrote, I should reopen that issue, but I don't know how this works.

There is the old/new issue right now:

@2.6 all options @ "firefox built in-page" result in "bookmarks-menu" and not the selected one.
2.4.0 runs fine @ firefox 61.0.1 64bit Win7
I would like to use the results in "bookmarks-toolbar"

"bookmarks-toolbar" flashs shortly and then still "bookmarks-menu"

Best regards

**Comment by teddy-gustiaux** [comment]
Hello! No problem, we can use the new issue you created. 🙂 

This does not seem to be a bug I can reproduce. Could you confirm the version of Firefox you are using? To make sure we are on the same page, this is what I understand:

- You set up the default bookmark folder for the built-in Firefox bookmarking to be *Bookmark Toolbar*
- When trying to add a bookmark via the built-in Firefox bookmarking icon, the opened dialog briefly shows the configured folder then changes to *Bookmarks Menu*

This is a strange issue, considering the *normal* default folder bookmark is *Other Bookmarks*. Could you check if you have any other extensions installed related to bookmarks? They could potentially conflict with this one.

Additionally, I do not know how familiar you are with _Firefox profiles_, but something you can try is creating a new clean profile, install the add-on and check if the problem is still present.

More information on profiles are available here:

- [Profiles - Where Firefox stores your bookmarks, passwords and other user data](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data)
- [Use the Profile Manager to create and remove Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)

**Comment by wulfstoe** [comment]
Hello, thanks for your response.

You understand total correctly, what I mean.

I use no other bookmark-extension or -script etc.

But you are right, my actually used profile is pretty old, maybe with any traces of tmp or else.

I could shortly checking the issue with a clean profie and than I post here, ok?

Best regards.

**Comment by wulfstoe** [comment]
Hello, 

with a clean profile and only "default-bookmark-folder" the issue is the same.

Best regards.

**Comment by teddy-gustiaux** [comment]
Thanks for trying that out! At least, now we know it is not because of the profile.

Could you tell me which version of Firefox you are using, and if it is a special edition (Web Developer, Nightly, Waterfox, etc.)? 

Additionally, could you confirm this problem happen with all types of pages and not specific ones, such as ones starting with `file://` or `about://`?

**Comment by wulfstoe** [comment]
Hello,

I use 64.0.2. 64bit quantum win7 64bit.

... all types of pages !

Best Regards.

**Comment by teddy-gustiaux** [comment]
Hello again!

I finally managed to get access to a Windows 7 machine. Using the latest version of the add-on and of Firefox, I was able to replicate part of the issue. This specific installation of Windows is in French, and I had the same issue when trying to bookmark multiple selected tabs (the folder will always default to "Bookmarks Menu").

However, I did not experience the brief flashing you mentioned nor had any issue for single page bookmarking. I have opened a new dedicated issue (#56) for this (as it appears to be language-specific) and will be releasing a fix soon. 

When the fix is released, if you could try the add-on again and see if it works then, it would be great! 🙂
Also, could you tell me if are you using Firefox in English or in another language? Thanks!

**Comment by teddy-gustiaux** [comment]
The new version `2.9.0` is now available and should fix the issue regarding the bookmarking of multiple selected tabs when the language of the browser is not English.

@wulfstoe Would it possible for you to try the add-on again (with the new version) and let me know if you are still experiencing issues? Thanks a lot! 🙂

**Comment by wulfstoe** [comment]
hello,

today its running fine, without this issue above, well done.

thanks a lot.

**Comment by teddy-gustiaux** [comment]
I am glad to hear it! Thank you for your feedback! 👍
