### ISSUE TITLE
default location overrides location specified via drag and drop

### ISSUE THREAD

**Issue by tmalch** [teddy-gustiaux/default-bookmark-folder#5]
Hi, 
At first, a very nice and simple extension but I got a little bug here, I believe. 
When I drag a tab into the bookmarks sidebar and drop it at some folder "x" the bookmark always appears in the specified default bookmark location "y".
Drag and drop works as expected when "Override default location" setting is turned off. 
FF 57.0 linux

**Comment by teddy-gustiaux** [comment]
Hello! Thank you for reporting this problem! And sorry I took a while to respond, I have been busy with life recently. 😃 

You are not the first one to experience this issue, and it actually also happens when using the "Bookmarks All Tabs..." feature. In both cases, this behavior was due to the way I was handling the newly created bookmarks.

I have fixed this problem in a recent commit (ec106f5). I am planning to publish a new version on AMO (probably this week-end) that will include this fix. I will post here again when I do so!

Again, thank you for your help! 👍

**Comment by teddy-gustiaux** [comment]
I have just published the version `2.1.0` on AMO that should fix this problem. Please let me know if you are still experiencing issues after the update to the new version!

**Comment by SebiderSushi** [comment]
I am currently able to reproduce this bug in Firefox 71.0 running Default Bookmark Folder 2.10.1

**Comment by teddy-gustiaux** [comment]
Thanks for reporting this @SebiderSushi!

I was able to reproduce the issue, but only with the "Bookmarks Menu" or the "Other Bookmarks" folder. The other folders were behaving as expected.
After more digging, I have created a dedicated issue #136 regarding this problem. Unfortunately, this is not something I am able to fix for now (please refer to the issue for all the details). 

While investigating this, I have also found another similar bug with manually created bookmarks via the bookmark sidebar or library context menu. They were being moved to the default bookmark location configured in the add-on settings. This has been solved by the recent commit [`cb1e8f7`](https://github.com/teddy-gustiaux/default-bookmark-folder/commit/cb1e8f754a4e2f0c7b79662470238a741ac97397) and will be released with the next version of the add-on (which should hopefully be available next week).

If you are experiencing issues with the drag and drop on the bookmark sidebar with other folders than "Bookmarks Menu" or "Other Bookmarks", please feel free to open a new issue. 🙂

**Comment by SebiderSushi** [comment]
Thank you for your time and your explanations!
