### ISSUE TITLE
feature request: option to have bookmark folders expanded by default

### ISSUE THREAD

**Issue by sojeri** [teddy-gustiaux/default-bookmark-folder#52]
would love to have the bookmarks folder always expanded.

my rationale:
- if I'm not choosing a different folder, it won't impact me because I'll hit enter right away.
- if I am choosing a folder, it's one less step. :)

**Comment by teddy-gustiaux** [comment]
Hello (and sorry the late response)!

Thanks for opening a new issue. From what I understand, you are referring to the bookmark folder tree that is available when bookmarking a page via the built-in system. You would like to have it expanded by default as per the screenshot below.

![Example_of_expanded_folder_tree_with_built-in_bookmarking](https://user-images.githubusercontent.com/26365722/57115996-3b225e80-6d20-11e9-976a-f719a81834b0.png)

That would be a nice thing to have indeed! 🙂 Unfortunately, since Firefox 57, it is no longer possible for the extensions to change the interface or the native behavior of Firefox in such a way. There is simply no API that would allow developers to do this, sorry.

On a side note, if you want to play around and change the interface of Firefox in depth, you can use something called [userChrome.css](https://www.howtogeek.com/334716/how-to-customize-firefoxs-user-interface-with-userchrome.css/). It is not helping in the context of your request, as the expansion of the folder tree requires both CSS and JavaScript to work properly, but you might find it useful in other situations. 🙂

**Comment by sojeri** [comment]
then I can only respond: Firefox 57+ :sob:

**Comment by teddy-gustiaux** [comment]
I understand how you feel- Firefox 57 has definitely changed things a lot. I also understand why Mozilla decided to take this path from an engineering point of view and I do believe it was the right long-term choice for the users and for the future of the browser itself. The add-on ecosystem is not the same as it was, but time is definitely making things better, and hopefully more APIs will be made available to the developers in order to reach the same level of customization we had previously.
(This is only my personal opinion of course.) 🙂 

I am going to close the issue. Please feel free to open another one if you have any other feature request or bug report to share. Thanks!
