### ISSUE TITLE
Support for Basilisk? (Legacy UXP)

### ISSUE THREAD

**Issue by autoteelar** [teddy-gustiaux/default-bookmark-folder#540]
i see this addon was made before 2018,  yet its not in the CAA archive (classic addons archive) and the earlier versions i get the error "Basilisk Does not Support WebExtensions." which shouldnt be the case as firefox in 2017 didnt even use webextensions, do you have any old .xpi files that still work or something? the fact it keeps setting it as "other bookmarks" instead of my own personal folder i made is really annoying. and there is no addon for this already, ive been looking everywhere, hense making this issue asking for help :D

**Comment by teddy-gustiaux** [comment]
Sorry for the late reply. The first version of this add-on was indeed released in late 2017, around the time where [Firefox 57 ("Firefox Quantum")](https://www.mozilla.org/en-US/firefox/57.0/releasenotes/) was released. It was the Firefox version that started to "exclusively supports extensions built using the WebExtension API" (direct quote from the release notes).

Since the beginning this add-on was built using only the WebExtension model and APIs, since it was going to be only one available. You will not find an XPI of the add-on because I have never built one. Sorry I cannot help you with this one!
