### ISSUE TITLE
Backup my Preferences !

### ISSUE THREAD

**Issue by Machou** [teddy-gustiaux/default-bookmark-folder#63]
Hi,

Will you be able to add an option to Export / Import the preferences of the addon?

Just in case if we have to reinstall Firefox for example.

Sincerely,
Machou

=====

Salut,

Pourrai-tu ajouter une option pour Exporter / Importer les préferences de l'addon ?

Au cas où si on doit reinstaller Firefox par exemple.

Cordialement,
Machou

**Comment by teddy-gustiaux** [comment]
Hello! 

Adding an export function is quite straightforward. The import one is a bit more complicating as the provided settings must be checked to ensure they are valid.

If someone reinstall Firefox, as long as the bookmarks are restored (via the [Firefox backup/restore feature](https://support.mozilla.org/en-US/kb/restore-bookmarks-from-backup-or-move-them#w_backup-and-restore), not via an HTML file) before, there should be no problem. Otherwise, if a folder is missing, the associated option can be reset to its default and an information message can be displayed to the user.

I am adding this to the roadmap. 🙂
